version: "3.8"

services:
  mongo:
    image: mongo:7.0
    container_name: user_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: userdb
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: user_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://root:nBi9TSQltZCa5sf69sLKpkRN@172.21.188.151:27017
      JWT_SECRET: 38007a7a046cd438be9fecd00a537ee9
      JWT_EXPIRES_IN: 1d
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: npm run start

volumes:
  mongo-data:
